# config/wafer_config.yaml
default_params:
  scope: 14
  marker_size: 0.7
  offset_x: -1.20840
  offset_y: 2.09301

type_specific_params:
  ML:
    scope: 14
    marker_size: 0.7
    offset_x: -1.20840
    offset_y: 2.09301
  MH:
    scope: 12
    marker_size: 0.5
    offset_x: 0.805403625519528
    offset_y: -1.395
  # Add other type codes with their specific parameters
  # If a parameter is not specified, it will use the default value

output_paths:
  cell_coordinate_json: "output/coordinates/{type_code}_wafer_coordinates.json"
  cell_id_mapping_json: "output/mapping/{type_code}_wafer_mapping.json"
  geometry_root_file: "output/geometry/{type_code}_wafer_geometry.root"
  output_name: "output/waferMaps/{type_code}_wafer_map.png"
